### ISSUE TITLE
 error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by breiti35** [hassan-sd/insta-face-scraper#1]
Hey 
the installation cannot be completed
` error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Partial import of sklearn during the build process.
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      Traceback (most recent call last):
        File "C:\Users\e_a_g\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\e_a_g\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\e_a_g\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\setuptools\build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 319, in <module>
        File "<string>", line 315, in setup_package
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
          config = configuration()
        File "<string>", line 201, in configuration
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1014, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 980, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 922, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-install-mqe_83q6\scikit-learn_a7fd66d060544e67983bb1e5f4e54379\sklearn\setup.py", line 85, in configuration
          cythonize_extensions(top_path, config)
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-install-mqe_83q6\scikit-learn_a7fd66d060544e67983bb1e5f4e54379\sklearn\_build_utils\__init__.py", line 47, in cythonize_extensions
          basic_check_build()
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-install-mqe_83q6\scikit-learn_a7fd66d060544e67983bb1e5f4e54379\sklearn\_build_utils\pre_build_helpers.py", line 113, in basic_check_build
          compile_test_program(code)
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-install-mqe_83q6\scikit-learn_a7fd66d060544e67983bb1e5f4e54379\sklearn\_build_utils\pre_build_helpers.py", line 70, in compile_test_program
          ccompiler.compile(
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\setuptools\msvc.py", line 210, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\e_a_g\AppData\Local\Temp\pip-build-env-02o595tv\overlay\Lib\site-packages\setuptools\msvc.py", line 164, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.`

**Comment by hassan-sd** [comment]
Download build tools: https://visualstudio.microsoft.com/visual-cpp-build-tools/

Then in the same folder where your EXE is, run this command:

`.\vs_BuildTools.exe --quiet --wait --norestart --nocache --installPath C:\BuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041`

or

`vs_BuildTools.exe --quiet --wait --norestart --nocache --installPath C:\BuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041`

Leave it running and you can see in your C:\BuildTools that new folders are being added. When it's finished, restart the PC and your package should install correctly
